db:
  image: postgres
  ports: 
    - "5432:5432"
redis:
  image: redis
web:
  build: .
  command: bundle exec rails s -p 5780 -b '0.0.0.0'
  volumes:
    - .:/myapp
  ports:
    - "5780:5780"
  links:
    - db
    - redis